"""assessment_schema

Revision ID: 03696b25837f
Revises: 23e884eecc7a
Create Date: 2026-09-20 22:16:28.235765

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03696b25837f"
down_revision: Union[str, None] = "23e884eecc7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("submission_id", sa.String(length=36), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("rule_version", sa.String(length=64), nullable=False),
        sa.Column("parameters_json", sa.Text(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("cutoff_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("findings_count", sa.Integer(), nullable=False),
        sa.Column("summary_counts_json", sa.Text(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["submission_id"], ["submissions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("analysis_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_analysis_runs_entity_id"), ["entity_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_analysis_runs_input_hash"), ["input_hash"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_analysis_runs_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_analysis_runs_submission_id"), ["submission_id"], unique=False
        )

    op.create_table(
        "findings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("submission_id", sa.String(length=36), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("proposition", sa.Text(), nullable=False),
        sa.Column("scope", sa.String(length=255), nullable=False),
        sa.Column("family", sa.String(length=64), nullable=False),
        sa.Column("direction", sa.String(length=32), nullable=False),
        sa.Column("evidence_state", sa.String(length=32), nullable=False),
        sa.Column("applicable_obligation", sa.Text(), nullable=False),
        sa.Column("supporting_sources_json", sa.Text(), nullable=False),
        sa.Column("contradicting_sources_json", sa.Text(), nullable=False),
        sa.Column("lineage_json", sa.Text(), nullable=False),
        sa.Column("unknowns_json", sa.Text(), nullable=False),
        sa.Column("alternative_explanations_json", sa.Text(), nullable=False),
        sa.Column("additional_evidence_needed_json", sa.Text(), nullable=False),
        sa.Column("metrics_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["analysis_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["submission_id"], ["submissions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_findings_entity_id"), ["entity_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_findings_evidence_state"), ["evidence_state"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_findings_family"), ["family"], unique=False)
        batch_op.create_index("ix_findings_run_family", ["run_id", "family"], unique=False)
        batch_op.create_index(batch_op.f("ix_findings_run_id"), ["run_id"], unique=False)
        batch_op.create_index("ix_findings_run_state", ["run_id", "evidence_state"], unique=False)
        batch_op.create_index(batch_op.f("ix_findings_scope"), ["scope"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_findings_submission_id"), ["submission_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_findings_submission_id"))
        batch_op.drop_index(batch_op.f("ix_findings_scope"))
        batch_op.drop_index("ix_findings_run_state")
        batch_op.drop_index(batch_op.f("ix_findings_run_id"))
        batch_op.drop_index("ix_findings_run_family")
        batch_op.drop_index(batch_op.f("ix_findings_family"))
        batch_op.drop_index(batch_op.f("ix_findings_evidence_state"))
        batch_op.drop_index(batch_op.f("ix_findings_entity_id"))

    op.drop_table("findings")
    with op.batch_alter_table("analysis_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analysis_runs_submission_id"))
        batch_op.drop_index(batch_op.f("ix_analysis_runs_status"))
        batch_op.drop_index(batch_op.f("ix_analysis_runs_input_hash"))
        batch_op.drop_index(batch_op.f("ix_analysis_runs_entity_id"))

    op.drop_table("analysis_runs")
    # ### end Alembic commands ###
