"""initial_schema

Revision ID: 23e884eecc7a
Revises:
Create Date: 2026-09-20 20:55:27.360017

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23e884eecc7a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cses",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cses_code"), ["code"], unique=True)

    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("entity_scope", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("csrf_token", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "submissions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_timezone", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("manifest_json", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["entity_id"], ["cses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("submissions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_submissions_entity_id"), ["entity_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_submissions_idempotency_key"), ["idempotency_key"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_submissions_status"), ["status"], unique=False)

    op.create_table(
        "raw_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("submission_id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=100), nullable=False),
        sa.Column("record_type", sa.String(length=64), nullable=False),
        sa.Column("row_locator", sa.String(length=100), nullable=False),
        sa.Column("sha256_hash", sa.String(length=64), nullable=False),
        sa.Column("raw_payload", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["submission_id"], ["submissions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("raw_records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_raw_records_source_id"), ["source_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_raw_records_submission_id"), ["submission_id"], unique=False
        )

    op.create_table(
        "submission_files",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("submission_id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=100), nullable=False),
        sa.Column("record_type", sa.String(length=64), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("sha256_hash", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("declared_row_count", sa.Integer(), nullable=False),
        sa.Column("actual_row_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["submission_id"], ["submissions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("submission_id", "source_id", name="uq_submission_file_source"),
    )
    with op.batch_alter_table("submission_files", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_submission_files_source_id"), ["source_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_submission_files_submission_id"), ["submission_id"], unique=False
        )

    op.create_table(
        "validation_issues",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("submission_id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=100), nullable=True),
        sa.Column("record_type", sa.String(length=64), nullable=True),
        sa.Column("row_locator", sa.String(length=100), nullable=True),
        sa.Column("issue_type", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["submission_id"], ["submissions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("validation_issues", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_validation_issues_issue_type"), ["issue_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_validation_issues_source_id"), ["source_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_validation_issues_submission_id"), ["submission_id"], unique=False
        )

    op.create_table(
        "normalized_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("raw_record_id", sa.String(length=36), nullable=False),
        sa.Column("submission_id", sa.String(length=36), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=100), nullable=False),
        sa.Column("record_type", sa.String(length=64), nullable=False),
        sa.Column("native_id", sa.String(length=255), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("normalized_data", sa.Text(), nullable=False),
        sa.Column("is_quarantined", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["raw_record_id"], ["raw_records.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["submission_id"], ["submissions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("normalized_records", schema=None) as batch_op:
        batch_op.create_index(
            "ix_normalized_entity_record_native",
            ["entity_id", "record_type", "native_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_normalized_records_entity_id"), ["entity_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_normalized_records_native_id"), ["native_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_normalized_records_raw_record_id"), ["raw_record_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_normalized_records_record_type"), ["record_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_normalized_records_source_id"), ["source_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_normalized_records_submission_id"), ["submission_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_normalized_records_timestamp"), ["timestamp"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("normalized_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_normalized_records_timestamp"))
        batch_op.drop_index(batch_op.f("ix_normalized_records_submission_id"))
        batch_op.drop_index(batch_op.f("ix_normalized_records_source_id"))
        batch_op.drop_index(batch_op.f("ix_normalized_records_record_type"))
        batch_op.drop_index(batch_op.f("ix_normalized_records_raw_record_id"))
        batch_op.drop_index(batch_op.f("ix_normalized_records_native_id"))
        batch_op.drop_index(batch_op.f("ix_normalized_records_entity_id"))
        batch_op.drop_index("ix_normalized_entity_record_native")

    op.drop_table("normalized_records")
    with op.batch_alter_table("validation_issues", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_validation_issues_submission_id"))
        batch_op.drop_index(batch_op.f("ix_validation_issues_source_id"))
        batch_op.drop_index(batch_op.f("ix_validation_issues_issue_type"))

    op.drop_table("validation_issues")
    with op.batch_alter_table("submission_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_submission_files_submission_id"))
        batch_op.drop_index(batch_op.f("ix_submission_files_source_id"))

    op.drop_table("submission_files")
    with op.batch_alter_table("raw_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_raw_records_submission_id"))
        batch_op.drop_index(batch_op.f("ix_raw_records_source_id"))

    op.drop_table("raw_records")
    with op.batch_alter_table("submissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_submissions_status"))
        batch_op.drop_index(batch_op.f("ix_submissions_idempotency_key"))
        batch_op.drop_index(batch_op.f("ix_submissions_entity_id"))

    op.drop_table("submissions")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_sessions_expires_at"))

    op.drop_table("sessions")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))

    op.drop_table("users")
    with op.batch_alter_table("cses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cses_code"))

    op.drop_table("cses")
    # ### end Alembic commands ###
