---
Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/sat-sa.local/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"

  - &RegulatorOrg
    Name: RegulatorOrg
    ID: RegulatorMSP
    MSPDir: crypto-config/peerOrganizations/regulator.nciipc.gov/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('RegulatorMSP.admin', 'RegulatorMSP.peer', 'RegulatorMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('RegulatorMSP.admin', 'RegulatorMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('RegulatorMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('RegulatorMSP.peer')"

  - &SupervisedOrg
    Name: SupervisedOrg
    ID: SupervisedMSP
    MSPDir: crypto-config/peerOrganizations/supervised.bank01.org/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('SupervisedMSP.admin', 'SupervisedMSP.peer', 'SupervisedMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('SupervisedMSP.admin', 'SupervisedMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('SupervisedMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('SupervisedMSP.peer')"

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_5: true

Application: &ApplicationDefaults
  Organizations:
  Policies:
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Read:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Write:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admin:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer.sat-sa.local:7050
  EtcdRaft:
    Consenters:
      - Host: orderer.sat-sa.local
        Port: 7050
        ClientTLSCert: crypto-config/ordererOrganizations/sat-sa.local/orderers/orderer.sat-sa.local/tls/server.crt
        ServerTLSCert: crypto-config/ordererOrganizations/sat-sa.local/orderers/orderer.sat-sa.local/tls/server.crt
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 100
    AbsoluteMaxBytes: 10 MB
    PreferredMaxBytes: 2 MB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  Capabilities:
    <<: *OrdererCapabilities

Channel: &ChannelDefaults
  Policies:
    Read:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Write:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admin:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  TwoOrgsApplicationGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *RegulatorOrg
        - *SupervisedOrg
      Capabilities: *ApplicationCapabilities
